version: '3'
services:
  mysql:
    image: mysql:8.0
    networks:
      - simplepay_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entripoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=roadseeker
      - MYSQL_USER=simplepay
      - MYSQL_PASSWORD=simplepay

  membership-service:
    image: study-architecture-membership-service:1.0.3
    networks:
      - simplepay_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
#    환경설정 파일(application.yaml)로 대체
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/simple_pay?useSSL=false&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=simplepay
#      - SPRING_DATASOURCE_PASSWORD=simplepay
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL57Dialect
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
#      - KAFKA_TASK_LOGGING_TOPIC=simplepay.logging.out.stdout

  banking-service:
    image: study-architecture-banking-service:1.0.0
    networks:
      - simplepay_network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
#    환경설정 파일(application.yaml)로 대체
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/simple_pay?useSSL=false&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=simplepay
#      - SPRING_DATASOURCE_PASSWORD=simplepay
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL57Dialect
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
#      - KAFKA_TASK_LOGGING_TOPIC=simplepay.logging.out.stdout
#      - MEMBERSHIP_SERVICE_URL=http://membership-service:8080

  money-service:
    image: study-architecture-money-service:1.0.0
    networks:
      - simplepay_network
    ports:
      - "8083:8080"
    depends_on:
      - mysql
#    환경설정 파일(application.yaml)로 대체
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/simple_pay?useSSL=false&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=simplepay
#      - SPRING_DATASOURCE_PASSWORD=simplepay
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL57Dialect
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
#      - KAFKA_TASK_CONSUMER_TOPIC=simplepay.task.result.topic
#      - KAFKA_TASK_PRODUCER_TOPIC=simplepay.task.topic
#      - KAFKA_TASK_LOGGING_TOPIC=simplepay.logging.out.stdout
#      - KAFKA_TASK_CONSUMER_GROUP_ID=simplepay.task.result.consumer
#      - KAFKA_ENABLE_AUTO_COMMIT=true
#      - KAFKA_AUTO_COMMIT_INTERVAL_MS=1000
#      - KAFKA_AUTO_OFFSET_RESET=earliest
#      - KAFKA_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
#      - KAFKA_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer


  remittance-service:
    image: study-architecture-remittance-service:1.0.0
    networks:
      - simplepay_network
    ports:
      - "8084:8080"
    depends_on:
      - mysql
  #    환경설정 파일(application.yaml)로 대체
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/simple_pay?useSSL=false&allowPublicKeyRetrieval=true
  #      - SPRING_DATASOURCE_USERNAME=simplepay
  #      - SPRING_DATASOURCE_PASSWORD=simplepay
  #      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL57Dialect
  #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
  #      - KAFKA_TASK_CONSUMER_TOPIC=simplepay.task.result.topic
  #      - KAFKA_TASK_PRODUCER_TOPIC=simplepay.task.topic
  #      - KAFKA_TASK_LOGGING_TOPIC=simplepay.logging.out.stdout
  #      - KAFKA_TASK_CONSUMER_GROUP_ID=simplepay.task.result.consumer
  #      - KAFKA_ENABLE_AUTO_COMMIT=true
  #      - KAFKA_AUTO_COMMIT_INTERVAL_MS=1000
  #      - KAFKA_AUTO_OFFSET_RESET=earliest
  #      - KAFKA_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
  #      - KAFKA_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer

  logging-service:
    image: study-architecture-logging-service:1.0.0
    networks:
      - simplepay_network
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_TASK_LOGGING_TOPIC=simplepay.logging.out.stdout

  task-consumer:
    image: study-architecture-task-consumer:1.0.0
    networks:
      - simplepay_network
    restart: always
    depends_on:
      - zookeeper
      - kafka
#    환경설정 파일(application.yaml)로 대체
#    environment:
#      - LOGGING_TOPIC=simplepay.logging.out.stdout
#      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
#      - KAFKA_TASK_CONSUMER_TOPIC=simplepay.task.topic
#      - KAFKA_TASK_RESULT_TOPIC=simplepay.task.result.topic
#      - KAFKA_TASK_CONSUMER_GROUP_ID=simplepay.task.consumer
#      - KAFKA_ENABLE_AUTO_COMMIT=true
#      - KAFKA_AUTO_COMMIT_INTERVAL_MS=1000
#      - KAFKA_AUTO_OFFSET_RESET=earliest
#      - KAFKA_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
#      - KAFKA_VALUE_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer

  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    networks:
      - simplepay_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  kafka:
    image: 'bitnami/kafka:3.4.1'
    networks:
      - simplepay_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=LC://kafka:29092,LX://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - simplepay_network
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

networks:
  simplepay_network:
    driver: bridge