version: '3'
services:
  mysql:
    image: mysql:8.0
    networks:
      - simplepay_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entripoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=roadseeker
      - MYSQL_USER=simplepay
      - MYSQL_PASSWORD=simplepay

  membership-service:
    image: study-architecture-membership-service:1.0.3
    networks:
      - simplepay_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/simple_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=simplepay
      - SPRING_DATASOURCE_PASSWORD=simplepay
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL57Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  banking-service:
    image: study-architecture-banking-service:1.0.0
    networks:
      - simplepay_network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/simple_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=simplepay
      - SPRING_DATASOURCE_PASSWORD=simplepay
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL57Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  money-service:
    image: study-architecture-money-service:1.0.0
    networks:
      - simplepay_network
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/simple_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=simplepay
      - SPRING_DATASOURCE_PASSWORD=simplepay
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL57Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


networks:
  simplepay_network:
    driver: bridge