spring:
  profiles:
    default: dev

---
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 9095

logging:
  topic: simplepay.logging.out.stdout

kafka:
  bootstrap:
    servers: localhost:9092
  consumer:
    group:
      id: simplepay.task.consumer
  task:
    topic: simplepay.task.topic
  enable:
    auto:
      commit: true
  auto:
    commit:
      interval:
        ms: 1000
    offset:
      reset: earliest
  key:
    deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value:
    deserializer: org.apache.kafka.common.serialization.StringDeserializer

membership:
  service:
    url: http://membership-service:8080

spring:
  config:
    activate:
      on-profile: local
#H2
  h2:
    console:
      enabled: true
      path: /h2-console
#Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: SA
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
